# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/kenny/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4203.106/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/kenny/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4203.106/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kenny/Work/DemoComplex

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kenny/Work/DemoComplex

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/kenny/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4203.106/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/kenny/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/181.4203.106/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kenny/Work/DemoComplex/CMakeFiles /home/kenny/Work/DemoComplex/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kenny/Work/DemoComplex/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DemoComplexTest

# Build rule for target.
DemoComplexTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DemoComplexTest
.PHONY : DemoComplexTest

# fast build rule for target.
DemoComplexTest/fast:
	$(MAKE) -f CMakeFiles/DemoComplexTest.dir/build.make CMakeFiles/DemoComplexTest.dir/build
.PHONY : DemoComplexTest/fast

#=============================================================================
# Target rules for targets named DemoComplex

# Build rule for target.
DemoComplex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DemoComplex
.PHONY : DemoComplex

# fast build rule for target.
DemoComplex/fast:
	$(MAKE) -f CMakeFiles/DemoComplex.dir/build.make CMakeFiles/DemoComplex.dir/build
.PHONY : DemoComplex/fast

Complex.o: Complex.cpp.o

.PHONY : Complex.o

# target to build an object file
Complex.cpp.o:
	$(MAKE) -f CMakeFiles/DemoComplexTest.dir/build.make CMakeFiles/DemoComplexTest.dir/Complex.cpp.o
	$(MAKE) -f CMakeFiles/DemoComplex.dir/build.make CMakeFiles/DemoComplex.dir/Complex.cpp.o
.PHONY : Complex.cpp.o

Complex.i: Complex.cpp.i

.PHONY : Complex.i

# target to preprocess a source file
Complex.cpp.i:
	$(MAKE) -f CMakeFiles/DemoComplexTest.dir/build.make CMakeFiles/DemoComplexTest.dir/Complex.cpp.i
	$(MAKE) -f CMakeFiles/DemoComplex.dir/build.make CMakeFiles/DemoComplex.dir/Complex.cpp.i
.PHONY : Complex.cpp.i

Complex.s: Complex.cpp.s

.PHONY : Complex.s

# target to generate assembly for a file
Complex.cpp.s:
	$(MAKE) -f CMakeFiles/DemoComplexTest.dir/build.make CMakeFiles/DemoComplexTest.dir/Complex.cpp.s
	$(MAKE) -f CMakeFiles/DemoComplex.dir/build.make CMakeFiles/DemoComplex.dir/Complex.cpp.s
.PHONY : Complex.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/DemoComplex.dir/build.make CMakeFiles/DemoComplex.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/DemoComplex.dir/build.make CMakeFiles/DemoComplex.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/DemoComplex.dir/build.make CMakeFiles/DemoComplex.dir/main.cpp.s
.PHONY : main.cpp.s

tests.o: tests.cpp.o

.PHONY : tests.o

# target to build an object file
tests.cpp.o:
	$(MAKE) -f CMakeFiles/DemoComplexTest.dir/build.make CMakeFiles/DemoComplexTest.dir/tests.cpp.o
.PHONY : tests.cpp.o

tests.i: tests.cpp.i

.PHONY : tests.i

# target to preprocess a source file
tests.cpp.i:
	$(MAKE) -f CMakeFiles/DemoComplexTest.dir/build.make CMakeFiles/DemoComplexTest.dir/tests.cpp.i
.PHONY : tests.cpp.i

tests.s: tests.cpp.s

.PHONY : tests.s

# target to generate assembly for a file
tests.cpp.s:
	$(MAKE) -f CMakeFiles/DemoComplexTest.dir/build.make CMakeFiles/DemoComplexTest.dir/tests.cpp.s
.PHONY : tests.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... DemoComplexTest"
	@echo "... DemoComplex"
	@echo "... Complex.o"
	@echo "... Complex.i"
	@echo "... Complex.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

